import pandas as pd
import psycopg2
from psycopg2 import Error
import pandas as pd
df=pd.DataFrame

try:
    # connect to db
    connection  = psycopg2.connect(
        host="***",
        port="***",
        database="***",
        user="d.tsipigin",
        password="***")

    # create a cursor
    cursor  = connection.cursor()
    # Распечатать сведения о PostgreSQL
    print("Информация о сервере PostgreSQL")
    print(connection.get_dsn_parameters(), "\n")
    # Выполнение SQL-запроса
    cursor.execute('''
        //query//
                    ''')
    record = cursor.fetchone()
    while record is not None:
        print(record)
        record = cursor.fetchone()
        # df.append(record)

except (Exception, Error) as error:
    print("Ошибка при работе с PostgreSQL", error)
finally:
    if connection:
        print("\nЗапрос к PostgreSQL выполнен ", record, "\n")
        cursor.close()
        connection.close()
        print("Соединение с PostgreSQL закрыто")

print (df)
